# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hmi-app"
BBFILE_PATTERN_hmi-app := "^${LAYERDIR}/"
BBFILE_PRIORITY_hmi-app = "7"

LAYERDEPENDS_hmi-app = "core qt6-layer"
LAYERVERSION_hmi-app = "1"
LAYERSERIES_COMPAT_hmi-app = "scarthgap"
