# Elevator HMI — project distro configuration
# Inherits poky distro as base.
require conf/distro/poky.conf

DISTRO = "elevator-hmi"
DISTRO_NAME = "Elevator HMI"
DISTRO_VERSION = "0.1"

# RAUC OTA update support (meta-rauc)
DISTRO_FEATURES:append = " rauc"

# No X11, no Wayland — single application EGLFS HMI
DISTRO_FEATURES:remove = "x11 wayland"
